/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : MQX1.c
**     Project     : ProcessorExpert
**     Processor   : MK60FN1M0VLQ12
**     Component   : MQX
**     Version     : Component 01.032, Driver 01.01, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-08-08, 17:46, # CodeGen: 1
**     Abstract    :
**         MQX RTOS Adapter component.
**     Settings    :
**          Component name                                 : MQX1
**          Settings                                       : 
**            RTOS adaptor                                 : 
**              Memory allocation                          : 
**                User function for memory allocation      : no
**                User function for memory deallocation    : no
**              Critical section                           : 
**                User function for entering critical section : no
**                User function for exiting critical section : no
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file MQX1.c
** @version 01.01
** @brief
**         MQX RTOS Adapter component.
*/         
/*!
**  @addtogroup MQX1_module MQX1 module documentation
**  @{
*/         

/* MODULE MQX1. */

#include "MQX1.h"

/* END MQX1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
