/*HEADER****************************************************************
*
* Copyright (c) 2008-2011 Freescale Semiconductor;
* All Rights Reserved
*
* Copyright (c) 2004-2009 Embedded Access Inc.;
* All Rights Reserved
*
* Copyright (c) 1989-2008 ARC International;
* All Rights Reserved
*
***************************************************************************** 
*
* THIS SOFTWARE IS PROVIDED BY FREESCALE "AS IS" AND ANY EXPRESSED OR
* IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL FREESCALE OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
* IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
* THE POSSIBILITY OF SUCH DAMAGE.
*
***************************************************************************** 
*
* Comments:  This file was generated by "gawk -f def2c.awk" script.
*
*END*******************************************************************/

#include <rtcsrtos.h>
#include <rtcs.h>
#include "snmpcfg.h"
#include "asn1.h"
#include "snmp.h"


#if RTCSCFG_ENABLE_SNMP && RTCSCFG_ENABLE_IP4

extern RTCSMIB_NODE MIBNODE_enterprises;

extern RTCSMIB_NODE MIBNODE_freescale;
extern const RTCSMIB_NODE MIBNODE_mqx;
extern const RTCSMIB_NODE MIBNODE_mqxKernel;
extern const RTCSMIB_NODE MIBNODE_mqxVersion;
extern const RTCSMIB_NODE MIBNODE_mqxRevision;
extern const RTCSMIB_NODE MIBNODE_mqxRevKernel;
extern const RTCSMIB_NODE MIBNODE_mqxRevPSP;
extern const RTCSMIB_NODE MIBNODE_mqxRevIO;
extern const RTCSMIB_NODE MIBNODE_mqxRevBSP;
extern const RTCSMIB_NODE MIBNODE_mqxCopyright;
extern const RTCSMIB_NODE MIBNODE_mqxDate;
extern const RTCSMIB_NODE MIBNODE_mqxCPU;
extern const RTCSMIB_NODE MIBNODE_mqxCPUType;
extern const RTCSMIB_NODE MIBNODE_mqxCPUEndian;
extern const RTCSMIB_NODE MIBNODE_mqxCPUAddressing;
extern const RTCSMIB_NODE MIBNODE_mqxProcessorNum;
extern const RTCSMIB_NODE MIBNODE_mqxConfig;
extern const RTCSMIB_NODE MIBNODE_mqxConfigFloatingPointIO;
extern const RTCSMIB_NODE MIBNODE_mqxConfigInlineMacros;
extern const RTCSMIB_NODE MIBNODE_mqxConfigKernelLogging;
extern const RTCSMIB_NODE MIBNODE_mqxConfigMonitorStack;
extern const RTCSMIB_NODE MIBNODE_mqxConfigTaskCreationBlocks;
extern const RTCSMIB_NODE MIBNODE_mqxConfigTaskDestruction;
extern const RTCSMIB_NODE MIBNODE_mqxConfigComponentDestruction;
extern const RTCSMIB_NODE MIBNODE_mqxConfigCheckErrors;
extern const RTCSMIB_NODE MIBNODE_mqxConfigCheckValidity;
extern const RTCSMIB_NODE MIBNODE_mqxConfigCheckAlloc;
extern const RTCSMIB_NODE MIBNODE_mqxConfig64BitInts;
extern const RTCSMIB_NODE MIBNODE_mqxConfigPspKernelLogging;
extern const RTCSMIB_NODE MIBNODE_mqxConfigPspFPRegisters;
extern const RTCSMIB_NODE MIBNODE_mqxConfig32BitQIDs;
extern const RTCSMIB_NODE MIBNODE_mqxTask;
extern const RTCSMIB_NODE MIBNODE_mqxTaskTable;
extern const RTCSMIB_NODE MIBNODE_mqxTaskEntry;
extern const RTCSMIB_NODE MIBNODE_mqxTaskID;
extern const RTCSMIB_NODE MIBNODE_mqxTaskCreator;
extern const RTCSMIB_NODE MIBNODE_mqxTaskName;
extern const RTCSMIB_NODE MIBNODE_mqxTaskState;
extern const RTCSMIB_NODE MIBNODE_mqxTaskErrorCode;
extern const RTCSMIB_NODE MIBNODE_mqxTaskSched;
extern const RTCSMIB_NODE MIBNODE_mqxTaskSchedPriority;
extern const RTCSMIB_NODE MIBNODE_mqxTaskSchedHomePriority;
extern const RTCSMIB_NODE MIBNODE_mqxTaskSchedPolicy;
extern const RTCSMIB_NODE MIBNODE_mqxTaskSchedTimeSlice;
extern const RTCSMIB_NODE MIBNODE_mqxTaskStackSize;
extern const RTCSMIB_NODE MIBNODE_mqxTaskStackUsed;
extern const RTCSMIB_NODE MIBNODE_mqxTaskIO;
extern const RTCSMIB_NODE MIBNODE_mqxTaskIOstdin;
extern const RTCSMIB_NODE MIBNODE_mqxTaskIOstdout;
extern const RTCSMIB_NODE MIBNODE_mqxTaskIOstderr;
extern const RTCSMIB_NODE MIBNODE_mqxTaskFlag;
extern const RTCSMIB_NODE MIBNODE_mqxTaskFlagFloatingPoint;
extern const RTCSMIB_NODE MIBNODE_mqxTaskFlagLoggingEnabled;
extern const RTCSMIB_NODE MIBNODE_mqxTaskFlagWatchdogEnabled;
extern const RTCSMIB_NODE MIBNODE_mqxTaskFlagPreemptionDisabled;
extern const RTCSMIB_NODE MIBNODE_mqxComponent;
extern const RTCSMIB_NODE MIBNODE_mqxComponentName;
extern const RTCSMIB_NODE MIBNODE_mqxComponentSem;
extern const RTCSMIB_NODE MIBNODE_mqxComponentEvent;
extern const RTCSMIB_NODE MIBNODE_mqxComponentMutex;
extern const RTCSMIB_NODE MIBNODE_mqxComponentTimer;
extern const RTCSMIB_NODE MIBNODE_mqxComponentLog;
extern const RTCSMIB_NODE MIBNODE_mqxComponentWatchdog;
extern const RTCSMIB_NODE MIBNODE_mqxComponentMessage;
extern const RTCSMIB_NODE MIBNODE_mqxComponentPart;
extern const RTCSMIB_NODE MIBNODE_mqxComponentIPC;
extern const RTCSMIB_NODE MIBNODE_mqxComponentQlog;
extern const RTCSMIB_NODE MIBNODE_mqxComponentEDS;
extern const RTCSMIB_NODE MIBNODE_mqxIOC;
extern const RTCSMIB_NODE MIBNODE_mqxIOCIO;
extern const RTCSMIB_NODE MIBNODE_mqxIOCRTCS;
extern const RTCSMIB_NODE MIBNODE_mqxIOCLAPB;
extern const RTCSMIB_NODE MIBNODE_mqxIOCLAPD;
extern const RTCSMIB_NODE MIBNODE_mqxIOCSDLC;
extern const RTCSMIB_NODE MIBNODE_mqxIOCHDLC;
extern const RTCSMIB_NODE MIBNODE_mqxIOCMFS;
extern const RTCSMIB_NODE MIBNODE_mqxIOCCAN;
extern const RTCSMIB_NODE MIBNODE_mqxIOCPPP;
extern const RTCSMIB_NODE MIBNODE_mqxIOCSNMP;
extern const RTCSMIB_NODE MIBNODE_mqxIOCENET;

extern const RTCSMIB_VALUE MIBVALUE_freescale;
extern const RTCSMIB_VALUE MIBVALUE_mqx;
extern const RTCSMIB_VALUE MIBVALUE_mqxKernel;
extern const RTCSMIB_VALUE MIBVALUE_mqxVersion;
extern const RTCSMIB_VALUE MIBVALUE_mqxRevision;
extern const RTCSMIB_VALUE MIBVALUE_mqxRevKernel;
extern const RTCSMIB_VALUE MIBVALUE_mqxRevPSP;
extern const RTCSMIB_VALUE MIBVALUE_mqxRevIO;
extern const RTCSMIB_VALUE MIBVALUE_mqxRevBSP;
extern const RTCSMIB_VALUE MIBVALUE_mqxCopyright;
extern const RTCSMIB_VALUE MIBVALUE_mqxDate;
extern const RTCSMIB_VALUE MIBVALUE_mqxCPU;
extern const RTCSMIB_VALUE MIBVALUE_mqxCPUType;
extern const RTCSMIB_VALUE MIBVALUE_mqxCPUEndian;
extern const RTCSMIB_VALUE MIBVALUE_mqxCPUAddressing;
extern const RTCSMIB_VALUE MIBVALUE_mqxProcessorNum;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfig;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigFloatingPointIO;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigInlineMacros;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigKernelLogging;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigMonitorStack;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigTaskCreationBlocks;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigTaskDestruction;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigComponentDestruction;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigCheckErrors;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigCheckValidity;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigCheckAlloc;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfig64BitInts;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigPspKernelLogging;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfigPspFPRegisters;
extern const RTCSMIB_VALUE MIBVALUE_mqxConfig32BitQIDs;
extern const RTCSMIB_VALUE MIBVALUE_mqxTask;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskTable;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskEntry;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskID;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskCreator;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskName;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskState;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskErrorCode;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskSched;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedPriority;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedHomePriority;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedPolicy;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedTimeSlice;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskStackSize;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskStackUsed;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskIO;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskIOstdin;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskIOstdout;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskIOstderr;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskFlag;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagFloatingPoint;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagLoggingEnabled;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagWatchdogEnabled;
extern const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagPreemptionDisabled;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponent;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentName;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentSem;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentEvent;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentMutex;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentTimer;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentLog;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentWatchdog;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentMessage;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentPart;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentIPC;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentQlog;
extern const RTCSMIB_VALUE MIBVALUE_mqxComponentEDS;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOC;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCIO;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCRTCS;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCLAPB;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCLAPD;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCSDLC;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCHDLC;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCMFS;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCCAN;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCPPP;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCSNMP;
extern const RTCSMIB_VALUE MIBVALUE_mqxIOCENET;

boolean MIB_find_mqxTaskEntry        (uint_32, pointer, pointer _PTR_);

static boolean MIB_instance_mqxTaskEntry        (RTCSMIB_WALK_PTR, uint_32, boolean (_CODE_PTR_)(uint_32, pointer, pointer _PTR_), boolean _PTR_, pointer _PTR_);


RTCSMIB_NODE MIBNODE_freescale = {
   33118,

   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqx,
   (RTCSMIB_NODE_PTR)&MIBNODE_enterprises,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqx = {
   1,

   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,
   (RTCSMIB_NODE_PTR)&MIBNODE_freescale,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxKernel = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTask,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxVersion,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxVersion = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevision,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxVersion,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxRevision = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCopyright,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevKernel,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxRevision,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxRevKernel = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevPSP,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxRevKernel,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxRevPSP = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevIO,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxRevPSP,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxRevIO = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevBSP,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxRevIO,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxRevBSP = {
   4,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxRevision,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxRevBSP,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxCopyright = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxDate,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_OCTET,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxCopyright,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxDate = {
   4,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCPU,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_OCTET,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxDate,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxCPU = {
   5,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxProcessorNum,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCPUType,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxCPU,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxCPUType = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCPUEndian,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCPU,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxCPUType,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxCPUEndian = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCPUAddressing,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCPU,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxCPUEndian,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxCPUAddressing = {
   3,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxCPU,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxCPUAddressing,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxProcessorNum = {
   6,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxProcessorNum,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfig = {
   7,

   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigFloatingPointIO,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxKernel,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfig,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigFloatingPointIO = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigInlineMacros,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigFloatingPointIO,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigInlineMacros = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigKernelLogging,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigInlineMacros,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigKernelLogging = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigMonitorStack,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigKernelLogging,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigMonitorStack = {
   4,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigTaskCreationBlocks,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigMonitorStack,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigTaskCreationBlocks = {
   5,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigTaskDestruction,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigTaskCreationBlocks,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigTaskDestruction = {
   6,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigComponentDestruction,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigTaskDestruction,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigComponentDestruction = {
   7,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigCheckErrors,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigComponentDestruction,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigCheckErrors = {
   8,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigCheckValidity,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigCheckErrors,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigCheckValidity = {
   9,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigCheckAlloc,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigCheckValidity,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigCheckAlloc = {
   10,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig64BitInts,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigCheckAlloc,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfig64BitInts = {
   11,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigPspKernelLogging,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfig64BitInts,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigPspKernelLogging = {
   12,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfigPspFPRegisters,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigPspKernelLogging,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfigPspFPRegisters = {
   13,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig32BitQIDs,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfigPspFPRegisters,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxConfig32BitQIDs = {
   14,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxConfig,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_zero, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxConfig32BitQIDs,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTask = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskTable,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskTable = {
   1,

   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTask,

   0,
   NULL,
   MIB_instance_zero, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskTable,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskEntry = {
   1,

   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskID,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskTable,

   0,
   MIB_find_mqxTaskEntry,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskEntry,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskID = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskCreator,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskID,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskCreator = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskName,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskCreator,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskName = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskState,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskName,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskState = {
   4,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskErrorCode,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskState,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskErrorCode = {
   5,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSched,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskErrorCode,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskSched = {
   6,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskStackSize,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSchedPriority,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   0,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskSched,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskSchedPriority = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSchedHomePriority,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskSchedPriority,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskSchedHomePriority = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSchedPolicy,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskSchedHomePriority,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskSchedPolicy = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSchedTimeSlice,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskSchedPolicy,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskSchedTimeSlice = {
   4,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskSched,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskSchedTimeSlice,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskStackSize = {
   7,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskStackUsed,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskStackSize,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskStackUsed = {
   8,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskIO,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskStackUsed,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskIO = {
   9,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlag,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskIOstdin,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   0,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskIO,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskIOstdin = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskIOstdout,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskIO,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskIOstdin,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskIOstdout = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskIOstderr,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskIO,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskIOstdout,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskIOstderr = {
   3,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskIO,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_OCTET,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskIOstderr,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskFlag = {
   10,

   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlagFloatingPoint,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskEntry,

   0,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_SEQUENCE,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskFlag,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskFlagFloatingPoint = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlagLoggingEnabled,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskFlagFloatingPoint,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskFlagLoggingEnabled = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlagWatchdogEnabled,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskFlagLoggingEnabled,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskFlagWatchdogEnabled = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlagPreemptionDisabled,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskFlagWatchdogEnabled,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxTaskFlagPreemptionDisabled = {
   4,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxTaskFlag,

   RTCSMIB_ACCESS_READ,
   NULL,
   MIB_instance_mqxTaskEntry, ASN1_TYPE_INTEGER,
   (RTCSMIB_VALUE_PTR)&MIBVALUE_mqxTaskFlagPreemptionDisabled,
   NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponent = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentName,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentName = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentSem,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentSem = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentEvent,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentEvent = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentMutex,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentMutex = {
   4,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentTimer,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentTimer = {
   5,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentLog,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentLog = {
   6,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentWatchdog,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentWatchdog = {
   7,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentMessage,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentMessage = {
   8,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentPart,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentPart = {
   9,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentIPC,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentIPC = {
   10,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentQlog,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentQlog = {
   11,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponentEDS,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxComponentEDS = {
   12,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxComponent,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOC = {
   4,

   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCIO,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqx,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCIO = {
   1,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCRTCS,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCRTCS = {
   2,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCLAPB,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCLAPB = {
   3,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCLAPD,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCLAPD = {
   4,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCSDLC,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCSDLC = {
   5,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCHDLC,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCHDLC = {
   6,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCMFS,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCMFS = {
   7,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCCAN,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCCAN = {
   8,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCPPP,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCPPP = {
   9,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCSNMP,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCSNMP = {
   10,

   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOCENET,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};

const RTCSMIB_NODE MIBNODE_mqxIOCENET = {
   11,

   NULL,
   NULL,
   (RTCSMIB_NODE_PTR)&MIBNODE_mqxIOC,

   0,
   NULL,
   NULL, 0, NULL, NULL
};


static boolean MIB_instance_mqxTaskEntry
   (
      RTCSMIB_WALK_PTR     mib,
      uint_32              op,
      boolean (_CODE_PTR_  find)(uint_32, pointer, pointer _PTR_),
      boolean _PTR_        found,
      pointer _PTR_        instance
   )
{ /* Body */
   struct {
      uint_32 mqxTaskID;
   } index;

   *found = FALSE;
   *instance = NULL;

   switch (op) {

   case RTCSMIB_OP_GET:
   case RTCSMIB_OP_SET:

      if (mib->inlen == 0) break;
      if (!RTCSMIB_id_read32(mib, &index.mqxTaskID)) return FALSE;
      if (mib->inlen != 0) break;
      *found = find(op, &index, instance);
      break;

   case RTCSMIB_OP_GETNEXT:
      if (mib->inlen == 0) {
         index.mqxTaskID = 0;
      } else {
         if (!RTCSMIB_id_read32(mib, &index.mqxTaskID)) return FALSE;
         if(index.mqxTaskID < 0xffffffff) // 4294967295
            index.mqxTaskID++;
      } /* Endif */
      *found = find(op, &index, instance);
      break;

   case RTCSMIB_OP_GETFIRST:
      index.mqxTaskID = 0;
      *found = find(RTCSMIB_OP_GETNEXT, &index, instance);
      break;
   } /* Endswitch */

   if (*found && (op != RTCSMIB_OP_SET)) {
      if (!RTCSMIB_id_write32 (mib, index.mqxTaskID)) return FALSE;
   } /* Endif */

   return TRUE;
} /* Endbody */


#endif

/****************************************************************************/

#if RTCSCFG_ENABLE_SNMP && RTCSCFG_ENABLE_IP4

#include <rtcs_prv.h>
#include "tcpip.h"

#include <mqx.h>
#include <fio.h>
#include <psp.h>
#include <mem_prv.h>
#include <mqx_prv.h>
#include <gen_rev.h>
#include <psp_rev.h>
#include <bsp_rev.h>
#include <stdlib.h>
#include <stddef.h>

extern uint_32 MIB_get_mqxConfig64BitInts(pointer dummy);
extern uint_32 MIB_get_mqxRevKernel(pointer dummy);
extern uint_32 MIB_get_mqxRevPSP(pointer dummy);
extern uint_32 MIB_get_mqxRevIO(pointer dummy);
extern uint_32 MIB_get_mqxRevBSP(pointer dummy);
extern uchar_ptr MIB_get_mqxCopyright(pointer td);
extern uchar_ptr MIB_get_mqxDate(pointer td);
extern uint_32 MIB_get_mqxCPUEndian(pointer dummy);
extern uint_32 MIB_get_mqxCPUAddressing(pointer dummy);
extern uint_32 MIB_get_mqxProcessorNum(pointer dummy);
static uint_32 MIB_get_mqxTaskID(pointer td);
static uint_32 MIB_get_mqxTaskCreator(pointer td);
static uchar_ptr MIB_get_mqxTaskName(pointer td);
static uint_32 MIB_get_mqxTaskState(pointer td);
static uint_32 MIB_get_mqxTaskErrorCode(pointer td);
static uint_32 MIB_get_mqxTaskSchedPriority(pointer td);
static uint_32 MIB_get_mqxTaskSchedHomePriority(pointer td);
static uint_32 MIB_get_mqxTaskSchedPolicy(pointer td);
static uint_32 MIB_get_mqxTaskSchedTimeSlice(pointer td);
static uint_32 MIB_get_mqxTaskStackSize(pointer dummy);
static uint_32 MIB_get_mqxTaskStackUsed(pointer dummy);
static uchar_ptr MIB_get_mqxTaskIOstdin(pointer td);
static uchar_ptr MIB_get_mqxTaskIOstdout(pointer td);
static uchar_ptr MIB_get_mqxTaskIOstderr(pointer td);
static uint_32 MIB_get_mqxTaskFlagFloatingPoint(pointer td);
static uint_32 MIB_get_mqxTaskFlagLoggingEnabled(pointer td);
static uint_32 MIB_get_mqxTaskFlagWatchdogEnabled(pointer td);
static uint_32 MIB_get_mqxTaskFlagPreemptionDisabled(pointer td);

/****************************************************************************/

uint_32 MIB_get_mqxConfig64BitInts(pointer dummy)
{
	return(0);	
}

boolean MIB_find_mqxTaskEntry
   (
      uint_32        op,
      pointer        index,
      pointer _PTR_  instance
   )
{ /* Body */
   KERNEL_DATA_STRUCT_PTR  kd_ptr = _mqx_get_kernel_data();
   _task_id                tid = (_task_id)*(uint_32_ptr)index;
   TD_STRUCT_PTR           td_ptr = NULL;
   QUEUE_ELEMENT_STRUCT_PTR search_ptr;
   uint_32                  td_num;

   if (op == RTCSMIB_OP_GET) {
      *instance = _task_get_td(tid);
      return (*instance != NULL);
   } /* Endif */

   search_ptr = kd_ptr->TD_LIST.NEXT;
   td_num = 0;
   for (;;) {
     td_ptr = (TD_STRUCT_PTR)((char_ptr)search_ptr - offsetof(TD_STRUCT, TD_LIST_INFO));
     if (td_ptr->TASK_ID >= tid) {
        break;
    } /* Endif */
    td_num++;
    if (td_num >= kd_ptr->TD_LIST.SIZE) {
        td_ptr = NULL;
        break;
    } /* Endif */
    search_ptr = search_ptr->NEXT;
   } /* Endfor */

   if (!td_ptr) {
      return FALSE;
   } /* Endif */

   *(uint_32_ptr)index = td_ptr->TASK_ID;
   *instance = td_ptr;
   return (td_ptr != NULL);

} /* Endbody */

static uint_32   MIB_get_mqxTaskID                     (pointer td) {return ((TD_STRUCT_PTR)td)->TASK_ID;}
static uint_32   MIB_get_mqxTaskCreator                (pointer td) {return ((TD_STRUCT_PTR)td)->PARENT;}
static uint_32   MIB_get_mqxTaskSchedTimeSlice         (pointer td) {uint_32 ms; _sched_get_rr_interval(((TD_STRUCT_PTR)td)->TASK_ID,&ms); return ms;}
static uchar_ptr MIB_get_mqxTaskName                   (pointer td) {return (uchar_ptr)((TD_STRUCT_PTR)td)->TASK_TEMPLATE_PTR->TASK_NAME;}
static uint_32   MIB_get_mqxTaskState                  (pointer td) {return ((TD_STRUCT_PTR)td)->STATE;}
static uint_32   MIB_get_mqxTaskErrorCode              (pointer td) {return ((TD_STRUCT_PTR)td)->TASK_ERROR_CODE;}
static uint_32   MIB_get_mqxTaskSchedPriority          (pointer td) {return ((TD_STRUCT_PTR)td)->MY_QUEUE->PRIORITY;}
static uint_32   MIB_get_mqxTaskSchedHomePriority      (pointer td) {return ((TD_STRUCT_PTR)td)->HOME_QUEUE->PRIORITY;}
static uint_32   MIB_get_mqxTaskSchedPolicy            (pointer td) {
#if MQX_TIME_SLICE_TASK
return (((TD_STRUCT_PTR)td)->FLAGS & MQX_TIME_SLICE_TASK) ? MQX_SCHED_RR : MQX_SCHED_FIFO;
#else
return 0;
#endif
}
#if MQX_KERNEL_LOGGING
static uint_32   MIB_get_mqxTaskStackSize              (pointer td) {uint_32 ss,su; _klog_get_task_stack_usage(((TD_STRUCT_PTR)td)->TASK_ID,&ss,&su); return ss;}
static uint_32   MIB_get_mqxTaskStackUsed              (pointer td) {uint_32 ss,su; _klog_get_task_stack_usage(((TD_STRUCT_PTR)td)->TASK_ID,&ss,&su); return su;}
#endif
static uchar_ptr MIB_get_mqxTaskIOstdin                (pointer td) {return (((TD_STRUCT_PTR)td)->STDIN_STREAM)  ? (uchar_ptr)((MQX_FILE_PTR)((TD_STRUCT_PTR)td)->STDIN_STREAM)->DEV_PTR->IDENTIFIER  : NULL;}
static uchar_ptr MIB_get_mqxTaskIOstdout               (pointer td) {return (((TD_STRUCT_PTR)td)->STDOUT_STREAM) ? (uchar_ptr)((MQX_FILE_PTR)((TD_STRUCT_PTR)td)->STDOUT_STREAM)->DEV_PTR->IDENTIFIER : NULL;}
static uchar_ptr MIB_get_mqxTaskIOstderr               (pointer td) {return (((TD_STRUCT_PTR)td)->STDERR_STREAM) ? (uchar_ptr)((MQX_FILE_PTR)((TD_STRUCT_PTR)td)->STDERR_STREAM)->DEV_PTR->IDENTIFIER : NULL;}
#if PSP_HAS_FPU
static uint_32   MIB_get_mqxTaskFlagFloatingPoint      (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & MQX_FLOATING_POINT_TASK)  ? 1 : 0;}
#endif
static uint_32   MIB_get_mqxTaskFlagLoggingEnabled     (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & TASK_LOGGING_ENABLED)     ? 1 : 0;}
static uint_32   MIB_get_mqxTaskFlagWatchdogEnabled    (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & TASK_WATCHDOG_STARTED)    ? 1 : 0;}
static uint_32   MIB_get_mqxTaskFlagPreemptionDisabled (pointer td) {return (((TD_STRUCT_PTR)td)->FLAGS & TASK_PREEMPTION_DISABLED) ? 1 : 0;}


uint_32 MIB_get_mqxRevKernel(pointer dummy)
{
	return(GEN_REVISION);
}

uint_32 MIB_get_mqxRevPSP(pointer dummy)
{
	return(PSP_REVISION);
}

uint_32 MIB_get_mqxRevIO(pointer dummy)
{
	return(IO_REVISION);
}

uint_32 MIB_get_mqxRevBSP(pointer dummy)
{
	return(BSP_REVISION);
}

uchar_ptr MIB_get_mqxCopyright(pointer td)
{
	return((uchar_ptr)_mqx_copyright);
}

uchar_ptr MIB_get_mqxDate(pointer td)
{
	return((uchar_ptr)_mqx_date );	
}

uint_32 MIB_get_mqxCPUEndian(pointer dummy)
{
	return(PSP_ENDIAN);	
}

uint_32 MIB_get_mqxCPUAddressing(pointer dummy)
{
	return(PSP_MEMORY_ADDRESSING_CAPABILITY);
}

uint_32 MIB_get_mqxProcessorNum(pointer dummy)
{
	//TBD KERNEL_DATA_STRUCT_PTR kd_ptr = _mqx_get_kernel_data();
	return 0;//((uint_32)kd_ptr->PROCESSOR_NUMBER);	
}

/****************************************************************************/

const RTCSMIB_VALUE MIBVALUE_mqxVersion = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_VERSION
};

const RTCSMIB_VALUE MIBVALUE_mqxRevKernel = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxRevKernel
};

const RTCSMIB_VALUE MIBVALUE_mqxRevPSP = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxRevPSP
};

const RTCSMIB_VALUE MIBVALUE_mqxRevIO = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxRevIO
};

const RTCSMIB_VALUE MIBVALUE_mqxRevBSP = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxRevBSP
};

const RTCSMIB_VALUE MIBVALUE_mqxCopyright = {
	RTCSMIB_NODETYPE_DISPSTR_FN,
	(void _PTR_)MIB_get_mqxCopyright 
};

const RTCSMIB_VALUE MIBVALUE_mqxDate = {
	RTCSMIB_NODETYPE_DISPSTR_FN,
	(void _PTR_)MIB_get_mqxDate 
};

const RTCSMIB_VALUE MIBVALUE_mqxCPUEndian = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxCPUEndian
};

const RTCSMIB_VALUE MIBVALUE_mqxCPUAddressing = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxCPUAddressing
};

const RTCSMIB_VALUE MIBVALUE_mqxProcessorNum = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxProcessorNum
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigFloatingPointIO = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_INCLUDE_FLOATING_POINT_IO
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigInlineMacros = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_USE_INLINE_MACROS
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigKernelLogging = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_KERNEL_LOGGING
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigMonitorStack = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_MONITOR_STACK
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigTaskCreationBlocks = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_TASK_CREATION_BLOCKS
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigTaskDestruction = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_TASK_DESTRUCTION
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigComponentDestruction = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_COMPONENT_DESTRUCTION
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigCheckErrors = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_CHECK_ERRORS
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigCheckValidity = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_CHECK_VALIDITY
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigCheckAlloc = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_CHECK_MEMORY_ALLOCATION_ERRORS
};

const RTCSMIB_VALUE MIBVALUE_mqxConfig64BitInts = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxConfig64BitInts
};

const RTCSMIB_VALUE MIBVALUE_mqxConfig32BitQIDs = {
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)MQX_USE_32BIT_MESSAGE_QIDS
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskID = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskID
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskCreator = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskCreator
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskName = {
	RTCSMIB_NODETYPE_DISPSTR_FN,
	(void _PTR_)MIB_get_mqxTaskName 
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskState = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskState
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskErrorCode = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskErrorCode
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedPriority = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskSchedPriority
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedHomePriority = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskSchedHomePriority
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedPolicy = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskSchedPolicy
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskSchedTimeSlice = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskSchedTimeSlice
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskStackSize = {
	#if MQX_KERNEL_LOGGING
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskStackSize
	#else
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)NULL
	#endif
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskStackUsed = {
	#if MQX_KERNEL_LOGGING
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskStackUsed
	#else
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)NULL
	#endif	
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskIOstdin = {
	RTCSMIB_NODETYPE_DISPSTR_FN,
	(void _PTR_)MIB_get_mqxTaskIOstdin 
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskIOstdout = {
	RTCSMIB_NODETYPE_DISPSTR_FN,
	(void _PTR_)MIB_get_mqxTaskIOstdout 
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskIOstderr = {
	RTCSMIB_NODETYPE_DISPSTR_FN,
	(void _PTR_)MIB_get_mqxTaskIOstderr 
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagFloatingPoint = {
#if PSP_HAS_FPU
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskFlagFloatingPoint
#else
	RTCSMIB_NODETYPE_UINT_CONST,
	(void _PTR_)NULL
#endif	
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagLoggingEnabled = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskFlagLoggingEnabled
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagWatchdogEnabled = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskFlagWatchdogEnabled
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskFlagPreemptionDisabled = {
	RTCSMIB_NODETYPE_UINT_FN,
	(void _PTR_)MIB_get_mqxTaskFlagPreemptionDisabled
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCLAPB = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigPspFPRegisters = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCPPP = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentPart = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskTable = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxTask = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxCPU = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxKernel = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCENET = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};


const RTCSMIB_VALUE MIBVALUE_mqxIOCLAPD = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentSem = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentEDS = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentQlog = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCHDLC = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCMFS = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentTimer = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponent = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentIPC = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentMutex = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskIO = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxConfigPspKernelLogging = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxConfig = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCSNMP = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCSDLC = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskSched = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxCPUType = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_freescale = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCCAN = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentLog = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskFlag = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxTaskEntry = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCRTCS = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxRevision = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqx = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOCIO = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxIOC = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentMessage = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentWatchdog = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentEvent = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

const RTCSMIB_VALUE MIBVALUE_mqxComponentName = {
	RTCSMIB_NODETYPE_INT_CONST,
	NULL
};

#endif /* RTCSCFG_ENABLE_SNMP && RTCSCFG_ENABLE_IP4 */

/****************************************************************************/
 
void MIBMQX_init(void)
{
#if RTCSCFG_ENABLE_SNMP && RTCSCFG_ENABLE_IP4
   RTCSMIB_mib_add(&MIBNODE_freescale);
#endif
}

/* EOF */
